import { type NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";

const SignIn: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <section className="flex min-h-screen items-center justify-center py-10">
        <div className="container text-center">
          <button
            type="button"
            className="inline-flex items-center gap-2 rounded-lg bg-blue-700 px-6 py-3 text-center font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
            onClick={() => void signIn("google", { callbackUrl: "/" })}
          >
            Login with Google
          </button>
        </div>
      </section>
    </>
  );
};

export default SignIn;
